### ISSUE TITLE
main.py: error: unrecognized arguments: --hr_image_size 384

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [HasnainRaz/Fast-SRGAN#1]
Hey, thanks for sharing. Is this possible to run in colab environment? I am getting this error when I try to run the sample script. I cloned, cdd to directory, and placed and pointed my own image directory within.

I get this error when I try to run it on 14 images I have resized to 384x384

thanks again

```
!python /content/Fast-SRGAN/main.py --image_dir '/content/Fast-SRGAN/imagedir' --hr_image_size 384 --lr 1e-4 --save_iter 200 --epochs 10 --batch_size 14

usage: main.py [-h] [--image_dir IMAGE_DIR] [--batch_size BATCH_SIZE]
               [--epochs EPOCHS] [--hr_size HR_SIZE] [--lr LR]
               [--save_iter SAVE_ITER]
main.py: error: unrecognized arguments: --hr_image_size 384
```

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
Nevermind, looks like you changed the command to hr_size.

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
meh looks like still going to have an issue with the model, probably needs to be loaded sequentially to work in colab

**Comment by HasnainRaz** [comment]
I'll update the command line doc in the readme.

To run you don't need to resize the images. Simply enter the the hr_size as whatever high res size you want to train on (384 is fine). The low res images will then automatically be generated during training. You don't need to do any preprocessing.

I'll add a notebook or a py file for inference to upsample your own images using the pretrained models.

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
Hey thanks, unfortunately I will have to find a way around this error 
https://github.com/tensorflow/tensorboard/issues/2106
https://github.com/tensorflow/tensorflow/issues/30609

before being able to run on colab, would love to run this for sure. just looks like it wont work on colab :/

**Comment by HasnainRaz** [comment]
You have to upgrade to tensorflow 2.0. You can also do that in a notebook by doing:

```bash
!pip uninstall tensorflow tensorflow-gpu tensorboard
```

and then do:
```bash
!pip install tensorflow-gpu
```

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
Thanks for the reply sir, still seems like I either get 10% mem exceeded error, or some such other error when running gpu2.0.0x

seems to be related to 
https://github.com/tensorflow/tensorflow/issues/28626
https://github.com/charlesq34/pointnet/issues/208

Colab probably will not work, I do appreciate you taking the time to reply though sir.

**Comment by HasnainRaz** [comment]
You can reduce the batch size or the image size to lower the memory consumption.

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
Yea, tried that.
