### ISSUE TITLE
More About Trained Model

### ISSUE THREAD

**Issue by hurkal** [HasnainRaz/Fast-SRGAN#10]
Hi. Thanks for this nice work.

I need some details about the pre-trained model. Could you give some detail about generator.h5 file? 
How many images did you use? Which pre-process operation applied?
How much time does it take to train? 
Is that the final version? Can we use it directly on our projects?

**Comment by HasnainRaz** [comment]
1. I used the div2k dataset (all images), no preprocessing.
2. About 2 days on a GTX1080.
3. It is, you can try it out for yourself. If it is not good enough for you, you can train on your own data/rebalance the weighting factor for the different losses and train your own from the provided code.
