### ISSUE TITLE
Easiest way to run inference from C/C++

### ISSUE THREAD

**Issue by Mark0zzz** [HasnainRaz/Fast-SRGAN#11]
I have images in memory in C++ that I would like to scale back to memory.  Ideally the whole environment to do this would be easy to distribute too.

From what I've found, it seems like I could convert the model to Tensorflow .pb and then run inference in openCV C++.

Does that sound like the simplest approach?  Wondering if anybody else did this already.

Thanks for the help!

**Comment by HasnainRaz** [comment]
I'm not too familiar with deploying to a C++ production environment. But generally, I know that the approach you are talking about is what people use. So you convert to protobuf which you can then infer with using C++

You might also look into tf-serving: https://www.tensorflow.org/tfx/guide/serving
Maybe this is more useful for you?
