### ISSUE TITLE
Way to make 2x instead of 4x?

### ISSUE THREAD

**Issue by Vancete** [HasnainRaz/Fast-SRGAN#14]
Hi there,

I'm trying to figure out if there's any way of make it output 2x images instead of 4x to win even more time.

Thanks for your awesome work.

**Comment by tvanhatalo** [comment]
Replace the 4s in the code by 2s where needed and remove an upsampling layer.

**Comment by HasnainRaz** [comment]
@tvanhatalo is half correct. You can remove one of the upsampling layers (deconv2d) inside the model. And feed the output of the first upsampling layer directly into the last layer. You have 2x upsampling now. You will however, need to retrain the model.

**Comment by reflare** [comment]
When using this approach, the training code returns an error:

`ValueError: Dimensions must be equal, but are 384 and 768 for '{{node mean_squared_error/SquaredDifference}} = SquaredDifference[T=DT_FLOAT](functional_5/conv2d_12/Tanh, y)' with input shapes: [7,384,384,3], [7,768,768,3].`

It seems that other parameters must be adjusted as well but it is unclear which ones. Any pointers would be appreciated.
