### ISSUE TITLE
Reproducing high FPS

### ISSUE THREAD

**Issue by roman-vygon** [HasnainRaz/Fast-SRGAN#15]
Thank you for this repository!

I'm trying to reproduce the FPS you wrote, I'm using 184x184 images, your pretrained model and the infer.py script. The time of inference should be <0.034s, but what I get is a consistent 0.4s.
I am using a worse graphics card, a GeForce 980, but I don't think that the decrease in time should be such drastic.

Increasing batch size doesn't work either, I still get 0.4s per image.

What am I doing wrong? What can I do to speedup inference?

**Comment by HasnainRaz** [comment]
The difference in timing is indeed due to your graphics card. The problem is that there is an architecture change between the gtx1080 and the geforce 980. Your's is maxwell, while 1080 is Pascal.

Cuda is known to contain optimizations specifically for the pascal, volta and future architectures that do the forward passes faster.

I have however been wanting to try out a half precision training scheme to make run a little bit faster, the problem is I don't have enough time to experiment with this. So if you come up with any optimizations, feel free to share.

**Comment by roman-vygon** [comment]
@HasnainRaz I had a friend run the infer.py example on a 1660 Ti, still 0.4s per image

**Comment by HasnainRaz** [comment]
Benchmarks show that 1660Ti is still slower than gtx 1080. On top of that the architecture is Turing.

If you bench it on a Pascal GPU and still get the same time, then I'd look into it, otherwise the difference is explained by the hardware.

**Comment by spacewalk01** [comment]
```
from argparse import ArgumentParser
from tensorflow import keras
import numpy as np
import cv2
import os
import time
import tensorflow as tf

parser = ArgumentParser()
parser.add_argument('--image_dir', type=str, help='Directory where images are kept.')
parser.add_argument('--output_dir', type=str, help='Directory where to output high res images.')

gpu_devices = tf.config.experimental.list_physical_devices('GPU')
for device in gpu_devices:
    tf.config.experimental.set_memory_growth(device, True)

def main():
    args = parser.parse_args()

    # Get all image paths
    image_paths = [os.path.join(args.image_dir, x) for x in os.listdir(args.image_dir)]
    num_imgs = len(image_paths)
    print('num of images:', num_imgs)
    # Change model input shape to accept all size inputs
    model = keras.models.load_model('models/generator.h5')
    inputs = keras.Input((None, None, 3))
    output = model(inputs)
    model = keras.models.Model(inputs, output)
    

    start_time = time.time()

    # Loop over all images
    for image_path in image_paths:
        
        # Read image
        low_res = cv2.imread(image_path, 1)

        # Convert to RGB (opencv uses BGR as default)
        low_res = cv2.cvtColor(low_res, cv2.COLOR_BGR2RGB)
        low_res = cv2.resize(low_res,(96, 96))

        # Rescale to 0-1.
        low_res = low_res / 255.0

        # Get super resolution image
        sr = model.predict(np.expand_dims(low_res, axis=0))[0]

        # Rescale values in range 0-255
        sr = (((sr + 1) / 2.) * 255).astype(np.uint8)

        # Convert back to BGR for opencv
        sr = cv2.cvtColor(sr, cv2.COLOR_RGB2BGR)

        # Save the results:
        cv2.imwrite(os.path.join(args.output_dir, os.path.basename(image_path)), sr)

    total_runtime = time.time() - start_time
    runtime = total_runtime / num_imgs

    print("Total runtime: %s seconds ---" % total_runtime)
    print("Single img: %s seconds ---" % runtime)

if __name__ == '__main__':
    main()
```

I have the same problem and tested it on RTX3070 with the provided 96x96 shaped model. The runtime is 0.048 seconds per image which is way slower than your results. Also, I appreciate it if you provide the model with 384x384 input

**Comment by HasnainRaz** [comment]
@spacewalk01 For the benchmark timing:

1 - Your benchmark includes times for reading and writing the images (disk IO) and color conversions. Usually these operations would be hidden on video frames as you can process a bunch of frames at the start, then start showing the results, then do IO for the next frames in parallel while the initial frames are being played. So please exclude them from the benchmark.

2 - You are downsizing to 96x96 which also takes some time, usually this wouldn't happen as you would just upscale whatever input size you got. This is also affecting your benchmark times.

3 - The initial few images/frames are slower in general, for benchmarks, it's better to ignore the time taken by the first 5 or 10 frames/images.


Also, the same code will run for any sized input, assuming your GPU has enough memory.

**Comment by spacewalk01** [comment]
```
    for image_path in image_paths:
        
        # Read image
        low_res = cv2.imread(image_path, 1)

        # Convert to RGB (opencv uses BGR as default)
        low_res = cv2.cvtColor(low_res, cv2.COLOR_BGR2RGB)
        low_res = cv2.resize(low_res,(96, 96))

        # Rescale to 0-1.
        low_res = low_res / 255.0
        
        start_time = time.time()

        # Get super resolution image
        sr = model.predict(np.expand_dims(low_res, axis=0))[0]

        end_time = time.time()
        runtime = end_time - start_time
        total_runtime += runtime

        # Rescale values in range 0-255
        sr = (((sr + 1) / 2.) * 255).astype(np.uint8)

        # Convert back to BGR for opencv
        sr = cv2.cvtColor(sr, cv2.COLOR_RGB2BGR)

        # Save the results:
        cv2.imwrite(os.path.join(args.output_dir, os.path.basename(image_path)), sr)
```
I used the above script for experiment excluding the read and write steps and got the following results. I tested it on 800 images from NTIRE dataset.
```
Total runtime: 27.659754753112793 seconds ---
Runtime per image: 0.03457469344139099 seconds ---
num of images: 800
```

**Comment by spacewalk01** [comment]
would you please share us models with larger input sizes such as  384x384 input image size for testing

**Comment by HasnainRaz** [comment]
> 

Good, seems like that improved things a bit. Could you now try turning off the tensorflow memory growth options. Let TF allocate all gpu memory, I suspect there might be some slowdowns there. Also please ignore the first few images times in your avg (add the times to a list, do an average on the times ignoring the first 10 times).

**Comment by HasnainRaz** [comment]
> would you please share us models with larger input sizes such as 384x384 input image size for testing

This script you have posted should work for input sizes 384x384 as you can see:

```python
inputs = keras.Input((None, None, 3))
output = model(inputs)
model = keras.models.Model(inputs, output)
```
The model's input is changed to be NONE in the spatial locations, which means any sized input is acceptable.

If you still have issues, it might be because you have a different version of tensorflow, in that case, look here: https://github.com/HasnainRaz/Fast-SRGAN/issues/27

**Comment by spacewalk01** [comment]
Unfortunately, it throws the following error processing 384x384 images:
```
 ValueError: Input 0 is incompatible with layer model_2: expected shape=(None, 96, 96, 3), found shape=(None, 384, 384, 3)
```

**Comment by HasnainRaz** [comment]
> Unfortunately, it throws the following error processing 384x384 images:
> 
> ```
>  ValueError: Input 0 is incompatible with layer model_2: expected shape=(None, 96, 96, 3), found shape=(None, 384, 384, 3)
> ```

Did you try the solution posted in #27
