### ISSUE TITLE
ImportError: cannot import name 'DataLoaderInfer'

### ISSUE THREAD

**Issue by farazBhatti** [HasnainRaz/Fast-SRGAN#2]
i am trying to run inference on my own images but keep getting this error. any suggestions?
`ImportError: cannot import name 'DataLoaderInfer
`
there is no class or function in dataloader.py of that name. may i am wrong , kindly correct...

**Comment by HasnainRaz** [comment]
Thanks for that, should be fixed now. Please pull again and try.

**Comment by farazBhatti** [comment]
Now  i am getting following error. should i open a new thread?
`ValueError: Unknown layer: TensorFlowOpLayer
`

**Comment by HasnainRaz** [comment]
What version of tensorflow are you using? because tensorflow 2 is required.

**Comment by farazBhatti** [comment]
hmm, i am using 1.13.1 .ok i ll update its version.Thanks!!
