### ISSUE TITLE
Image was white until I made this change

### ISSUE THREAD

**Issue by mpottinger** [HasnainRaz/Fast-SRGAN#22]
Hello, just letting you know I needed to make this change to the inference code in order for the output to display properly. I upgraded a few of the dependencies to the latest versions and maybe that is why. Or possibly because I converted infer.py to use live webcam images. I am using:

Tensorflow 2.3.1
Python 3.8
OpenCV 4.40
Numpy 1.18.5

I needed to make one small change to the inference code, otherwise the image was just all white
`        # Rescale values in range 0-255

sr = ((sr + 1.0) / 2.0) * 255.0

sr = sr.astype(np.uint8)  # image is all white without this line

# Convert back to BGR for opencv

sr = cv2.cvtColor(sr, cv2.COLOR_RGB2BGR)

`

**Comment by HasnainRaz** [comment]
Good call, I will fix this

**Comment by HasnainRaz** [comment]
Fixed, closing
