### ISSUE TITLE
infer.py not working in the same dependencies...

### ISSUE THREAD

**Issue by WilburZjh** [HasnainRaz/Fast-SRGAN#25]
Stuck at this for a while...W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 491520000 exceeds 10% of system memory.

Btw, when I train my own data, do I need to have the high resolution and low resolution data and put them together in the same folder?

**Comment by HasnainRaz** [comment]
^ this error message is basically saying you are running out of memory when doing infer. Are you using very large images to do inference? If so, it's generally only possible to feed in images that your GPU memory can handle. If you really want to feed in very large images, you can crop them into manageable pieces, super res them, then join them together once all crops have been super resolution-ed.

When you train on your own data, you only need a directory of high res images. The low res images are generated automatically during training from the high res ones.
