### ISSUE TITLE
Training for Higher Upsampling Levels

### ISSUE THREAD

**Issue by reflare** [HasnainRaz/Fast-SRGAN#26]
I have made some changes to the code following this issue's advice:
https://github.com/HasnainRaz/Fast-SRGAN/issues/14

However, when removing or adding upsampling layers to the model and attempting to train a new model from scratch the following error is shown:
`ValueError: Dimensions must be equal, but are 384 and 768 for '{{node mean_squared_error/SquaredDifference}} = SquaredDifference[T=DT_FLOAT](functional_5/conv2d_12/Tanh, y)' with input shapes: [7,384,384,3], [7,768,768,3]`

This indicates that the sizes and ratios are hardcoded elsewhere. Could you point out what other parameters will need to be updated? If yes, then I'd be happy to provide a pull request with the changes needed for arbitrary scaling factors in return once it's done.

**Comment by HasnainRaz** [comment]
You will need to also adjust the dataloader to produce low res data at the new scale. Currently the dataloader is programmed to downscale the high res images by 4 to produce low res samples.

Have a look at the function in line 62 in dataloader.py

Hope this clears up the confusion

**Comment by reflare** [comment]
@HasnainRaz Thank you. Works like a charm now!

If anyone else is trying to accomplish the same thing, the lines you need to update are 
1) the two under the "Upsampling" in model.py. e.g.
```
# Upsampling
u1 = deconv2d(c2)
u1a = deconv2d(u1)
u1b = deconv2d(u1a)
u2 = deconv2d(u1b)
```

2) The LR heights and widths at the top of model.py. e.g.
```
self.lr_height = self.hr_height // 16  # Low resolution height
self.lr_width = self.hr_width // 16  # Low resolution width
```

3) The data loader sizes. e.g.
```
low_res = tf.image.resize(high_res, 
                                  [self.image_size // 16, self.image_size // 16], 
                                  method='bicubic')
```
