### ISSUE TITLE
ValueError: Input 0 is incompatible with layer model_2: expected shape=(None, 96, 96, 3), found shape=(None, 480, 640, 3) from infer.py

### ISSUE THREAD

**Issue by KyungbokLee** [HasnainRaz/Fast-SRGAN#27]
First, thank you for your great work.
I have tried to enhance my images of shape 640x480 using the pretrained model, but infer.py returns an error:

ValueError: Input 0 is incompatible with layer model_2: expected shape=(None, 96, 96, 3), found shape=(None, 480, 640, 3)

The model works only if I change the input image to 384x384, which is the original value used when training the model.

I've read 'Changing Input Size' from README, but the modification seems to be already applied on infer.py.

Also, when I load the pretrained model, there is a warning:

WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually. 

I'm using the latest version of tensorflow-gpu : 2.4.0.

**Comment by KyungbokLee** [comment]
I somehow managed to change the input size, using https://colab.research.google.com/drive/1s1lkOiqKgl9_MsXJtPF--oh6uXHYkNYm#scrollTo=dV7a_Jca4cgC.

**Comment by HasnainRaz** [comment]
Thank you for letting me know. It appears the tensorflow api has changed a lot since this repo was published (it is meant to be used with tensorflow 2.0). I will update the codebase whenever I have time. But for now I will prioritize the pytorch migration.

**Comment by minikiller** [comment]
@KyungbokLee i face the same error as you,how to fix this error i still do not know! Can you give me some help? Thanks!

**Comment by HasnainRaz** [comment]
@minikiller try:

```python
def change_model(model, new_input_shape=(None, 40, 40, 3),custom_objects=None):
    # replace input shape of first layer
    
    config = model.layers[0].get_config()
    config['batch_input_shape']=new_input_shape
    model._layers[0]=model.layers[0].from_config(config)

    # rebuild model architecture by exporting and importing via json
    new_model = tensorflow.keras.models.model_from_json(model.to_json(),custom_objects=custom_objects)

    # copy weights from old model to new one
    for layer in new_model._layers:
        try:
            layer.set_weights(model.get_layer(name=layer.name).get_weights())
            print("Loaded layer {}".format(layer.name))
        except:
            print("Could not transfer weights for layer {}".format(layer.name))

    return new_model

model = keras.models.load_model('models/generator.h5')
model = change_model(model, new_input_shape=[None, None, None, 3])
```

Then try to super resolve your image

**Comment by minikiller** [comment]
@HasnainRaz  Thanks very much for your help.  But I found when I infer my image it can not work like what readme.md showed. I don't know why! Can you help me? Thanks again!

**Comment by HasnainRaz** [comment]
I think it is simply because you are using an older version of TensorFlow. If you upgrade, you might have the same problem as Kyung

**Comment by anufagbemi** [comment]
Hello @HasnainRaz,
I am experiencing the same problem as @KyungbokLee even with the use of change_model for the input image. Could you please provide more clarity on how you will run that code snippet along with the existing infer.py? Thanks.

**Comment by HasnainRaz** [comment]
@anufagbemi  The easiest thing to do at this time would be to downgrade to tensorflow version 2.0.3, this should make the original snippet for changing input shape work.

I will have to catch up on tensorflow's new api to answer this question, but this repo as of now only supports tensorflow 2.0.3 as can be seen in the "requirements.txt" file.

**Comment by anufagbemi** [comment]
Unfortunately, I'm using one of the high-end gpus which require the use of the development TensorFlow versions (e.g. 2.8.0), so that won't work. Anyway, I'll see what I can do. Also, let me know if you were able to edit the code.
