### ISSUE TITLE
how to process sr in real time speed for developing video cam

### ISSUE THREAD

**Issue by ComradeMack** [HasnainRaz/Fast-SRGAN#34]
I extract 30-second video into images with 60 fps (480x360). Then I try to run infer.py to get super resolution frames and get the frames combined into video again. The converting process is not that slow. But the inference processing really takes along time nearly 1 hour. I aim to develop models for real time super resolution webcam. I need to get the inference time as fast as video duration(30 second) or faster. What is your suggestions?

**Comment by HasnainRaz** [comment]
As you can see in the table on the readme, an input size of 256x256 will give you around 30fps.

I assume you are already running this on a gpu, if not, please do so.

You can also check if the reading/writing of images is being a bottleneck, for which you can use async functions.
