### ISSUE TITLE
Running the model in Real time with webcam 

### ISSUE THREAD

**Issue by ganapathi12** [HasnainRaz/Fast-SRGAN#38]
hi @HasnainRaz , the information and the model you provide is really fantastic, could you please guide me or provide me some instructions on how to run this model on webcam, or any better way to run on a real time device, i am trying to implement this on 2070 super gpu

**Comment by HasnainRaz** [comment]
You can easily get your webcam feed using opencv: https://subscription.packtpub.com/book/application-development/9781785283932/3/ch03lvl1sec28/accessing-the-webcam

Then you just need to input the frame to the model.
