### ISSUE TITLE
SRGAN beginner

### ISSUE THREAD

**Issue by eshwarkamal** [HasnainRaz/Fast-SRGAN#42]
Hello Hasnainraz,
It's really cool to see your SRGAN work. Could you link the dataset source and minimum requirement of GPU series to achieve the final model like you?
It would be a huge help for beginners, including me.

**Comment by HasnainRaz** [comment]
The dataset used is DIV2K: https://data.vision.ee.ethz.ch/cvl/DIV2K/

GPU used was a GTX1080, So you'll need around 8GB of gpu memory to train it on the default settings. You could reduce this by reducing the batch size in the config.

**Comment by eshwarkamal** [comment]
> The dataset used is DIV2K: https://data.vision.ee.ethz.ch/cvl/DIV2K/
> 
> GPU used was a GTX1080, So you'll need around 8GB of gpu memory to train it on the default settings. You could reduce this by reducing the batch size in the config.

Hi, I successfully executed your code, but it accepts only 96x96 images

**Comment by HasnainRaz** [comment]
Please see: https://github.com/HasnainRaz/Fast-SRGAN/issues/27

**Comment by eshwarkamal** [comment]
> Please see: #27

I can't get it @HasnainRaz , still receive this error 

> ValueError: Input 0 is incompatible with layer model_2: expected shape=(None, 96, 96, 3), found shape=(None, 384, 384, 3)

**Comment by EvelyneCalista** [comment]
> > Please see: #27
> 
> I can't get it @HasnainRaz , still receive this error
> 
> > ValueError: Input 0 is incompatible with layer model_2: expected shape=(None, 96, 96, 3), found shape=(None, 384, 384, 3)

hi, have you successfully resolve this problem? thank you.

**Comment by eshwarkamal** [comment]
> > > Please see: #27
> > 
> > I can't get it @HasnainRaz , still receive this error
> > 
> > > ValueError: Input 0 is incompatible with layer model_2: expected shape=(None, 96, 96, 3), found shape=(None, 384, 384, 3)
> 
> hi, have you successfully resolve this problem? thank you.

No @EvelyneCalist , i tried but it didn't support.
I moved to another repository.
