### ISSUE TITLE
Incompatible shape

### ISSUE THREAD

**Issue by MattiaMartinelliGeo** [HasnainRaz/Fast-SRGAN#44]
Good morning,
thank you for the great work.
I am trying to run my code on my own image.
To change input size I run the code you suggested: 

from tensorflow import keras

# Load the model
model = keras.models.load_model('models/generator.h5')

# Define arbitrary spatial dims, and 3 channels.
inputs = keras.Input((None, None, 3))

# Trace out the graph using the input:
outputs = model(inputs)

# Override the model:
model = keras.models.Model(inputs, outputs)

# Now you are free to predict on images of any size.

However I still have this error, 
Input 0 of layer "model_2" is incompatible with the layer: expected shape=(None, 96, 96, 3), found shape=(None, 11, 11, 3)

same thing if I run the infer.py command.
Any suggestion how to solve it?

thank you very much

**Comment by plehman2000** [comment]
Same issue encountered when attempting to upscale images of  size mentioned in original commit.
![Screenshot from 2022-05-05 14-38-37](https://user-images.githubusercontent.com/54288924/166998458-5f65edba-b830-4823-9132-519019774485.png)

**Comment by plehman2000** [comment]
Apologies! I was using the incorrect version of tensorflow and h5py.
Doing ```pip install -r requirements.txt``` and ```pip install 'h5py==2.10.0' --force-reinstall``` allowed me to run it.

**Comment by HasnainRaz** [comment]
@MattiaMartinelliGeo Please look at the response above. If that doesn't resolve it, look here: https://github.com/HasnainRaz/Fast-SRGAN/issues/27

**Comment by MattiaMartinelliGeo** [comment]
@HasnainRaz thank you very much,
