### ISSUE TITLE
Training requirements?

### ISSUE THREAD

**Issue by tjasmin111** [HasnainRaz/Fast-SRGAN#53]
Interesting repo. Can you please provide more details about the training process? Like, what data/images do we need for training? Is it only some images? For instance, I want to train on CG images. 

`python main.py --image_dir 'path/to/image/directory' --hr_size 384 --lr 1e-4 --save_iter 200 --epochs 10 --batch_size 14`

**Comment by HasnainRaz** [comment]
The images you want to train on should be RGB, and placed in the directory you specify with --image_dir argument. Please make sure to install the requirements file before doing this as this repo uses a very old version of tensorflow and newer versions will have issues.

Everything else should work if you use the command you listed. If you any specific question, raise another issue
