### ISSUE TITLE
The model file does not match your network

### ISSUE THREAD

**Issue by XiuSdk** [HasnainRaz/Fast-SRGAN#54]
The Upsample layer is different between your model file and you network, please check!

**Comment by HasnainRaz** [comment]
Hey @XiuSdk , this repository is not maintained anymore. There have been some pushes to it which upgraded tensorflow versions. I'm not sure if the compatibility issues are arising from that.
I would recommend to only use this repo if you want to train a model from scratch. Even then there are possibly better maintained repos out there so maybe use those first.

I will try to bring this repo up to date at some point. But currently cannot provide any timelines. I will update the readme with this information.
