### ISSUE TITLE
2x upscaling?

### ISSUE THREAD

**Issue by luikaire** [HasnainRaz/Fast-SRGAN#56]
Is there a way to upscale by 2x, instead of the default 4x, since 2x upscaling should be faster?
Setting scale_factor to 2 in configs/config.yaml doesn't seem to change anything

**Comment by HasnainRaz** [comment]
@luikaire Yeah, the config is only used to rescale images, not change the architecture of the network.

I agree that 2x will be faster. To do this you can do the following:

1. Remove one upscaling block (comment out this line): https://github.com/HasnainRaz/Fast-SRGAN/blob/master/model.py#L99
2. Set scale factor to 2 in the config

Then retrain the network on your images, should work.
