### ISSUE TITLE
improve quality of high-crf videos?

### ISSUE THREAD

**Issue by luikaire** [HasnainRaz/Fast-SRGAN#58]
I understand that the goal of this project is to upscale videos efficiently (and it does that fairly well). 

However, would it also be possible to use the same architecture (with scale_factor=1 and retraining, maybe?) to convert videos encoded in h264/h265/vp9/av1 at high crf (small size but worse video quality) into better quality videos 

The idea would be to save  bandwidth by downloading high-crf (much smaller size/worse quality) videos, then use this project to convert that downloaded video to a better quality one. Keeping scale_factor=1 (no upscaling) might also allow faster processing

Is this achievable. If so, any suggestions on how to go about this? 
thanks

**Comment by HasnainRaz** [comment]
This seems totally doable. You will have to adjust the dataloading pipeline such that it doesn't produce the low res/high res samples, instead produces your low quality, high quality pairs. Then modify the model and remove the two upsampling blocks. Training should work from there.
