### ISSUE TITLE
Question about training params

### ISSUE THREAD

**Issue by dcnhan** [HasnainRaz/Fast-SRGAN#8]
Hi, Thank you very much for your great work.

I tried to retrain the model using DIV2K data. However, after running about 100 epochs, I still see the checkboard artifacts in the generated images. Could you provide your training params of the pretrained model?

Thanks

**Comment by HasnainRaz** [comment]
Thank you for the information.

It was my mistake, I accidentally left an experimental piece of code in there. The upsampling layer was a subpixel conv. It's now changed.

Please pull the latest changes and try again.

Sorry for the inconvenience!

**Comment by dcnhan** [comment]
Thank you very much for your feedback.
